name: 🚀 Deploy

on:
  push:
    branches:
      - master
      - production

jobs:
  deploy-master:
    if: github.ref == 'refs/heads/master'
    name: 🎉 Deploy to Master
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Configure PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, intl, zip

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files to Master Server
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

  deploy-production:
    if: github.ref == 'refs/heads/production'
    name: 🎉 Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Configure PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, intl, zip

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files to Production Server
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ${{ secrets.FTP_PRODUCTION_SERVER }}
          username: ${{ secrets.FTP_PRODUCTION_USERNAME }}
          password: ${{ secrets.FTP_PRODUCTION_PASSWORD }}
